# **Project Overview**

This project focuses on predicting loan defaults using customer application data and historical credit behavior. The workflow includes data cleaning, feature aggregation, feature selection, machine learning model comparison, hyperparameter tuning, and threshold optimization. The final goal is to identify customers who are more likely to default while prioritizing effective default detection.

In [79]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import (
    roc_auc_score,
    recall_score,
    precision_score,
    f1_score,
    confusion_matrix,
    classification_report
)


from sklearn.model_selection import RandomizedSearchCV
import joblib

## MERGING ALL THE 7 FILES

In [2]:
# main_df = pd.read_csv('cleaned_application_train.csv')

In [3]:
# bureau = pd.read_csv('bureau_aggregated.csv')
# bureau_balance = pd.read_csv('bureau_balance_aggregated.csv')
# previous_app = pd.read_csv('previous_application_aggregated.csv')
# pos_cash = pd.read_csv('pos_cash_aggreagate.csv')
# credit_card = pd.read_csv('credit_card_aggregated.csv')
# installments = pd.read_csv('installments_aggregated.csv')

In [4]:
# print(bureau.columns.tolist())
# print(bureau_balance.columns.tolist())
# print(previous_app.columns.tolist())
# print(pos_cash.columns.tolist())
# print(credit_card.columns.tolist())
# print(installments.columns.tolist())

In [5]:
# final_df = (
#     main_df
#     .merge(bureau, on='SK_ID_CURR', how='left')
#     .merge(bureau_balance, on='SK_ID_CURR', how='left')
#     .merge(previous_app, on='SK_ID_CURR', how='left')
#     .merge(pos_cash, on='SK_ID_CURR', how='left')
#     .merge(credit_card, on='SK_ID_CURR', how='left')
#     .merge(installments, on='SK_ID_CURR', how='left')
# )

In [6]:
# print("Shape:", final_df.shape)

# print(
#     "Duplicate customers:",
#     final_df['SK_ID_CURR'].duplicated().sum()
# )

# print(
#     "Unique customers:",
#     final_df['SK_ID_CURR'].nunique()
# )

In [7]:
# # SAVING THE FINAL FILE
# final_df.to_csv(
#     'final_modeling_dataset.csv',
#     index=False
# )

### LOADING THE FINAL FILE

In [8]:
df = pd.read_csv('final_modeling_dataset.csv')

In [9]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [10]:
df.shape

(307507, 262)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307507 entries, 0 to 307506
Columns: 262 entries, SK_ID_CURR to INSTALL_PAYMENT_COMPLETION_RATIO
dtypes: float64(207), int64(39), object(16)
memory usage: 614.7+ MB

In [12]:
df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,AGE,YEARS_EMPLOYED,INCOME_PER_FAMILY_MEMBER,CREDIT_INCOME_RATIO,ANNUITY_INCOME_RATIO,ANNUITY_CREDIT_RATIO,BUREAU_TOTAL_LOANS,BUREAU_DAYS_CREDIT_MIN,BUREAU_DAYS_CREDIT_MAX,BUREAU_DAYS_CREDIT_MEAN,BUREAU_OVERDUE_DAYS_MAX,BUREAU_OVERDUE_DAYS_MEAN,BUREAU_TOTAL_CREDIT,BUREAU_AVG_CREDIT,BUREAU_MAX_CREDIT,BUREAU_TOTAL_DEBT,BUREAU_AVG_DEBT,BUREAU_MAX_DEBT,BUREAU_TOTAL_OVERDUE,BUREAU_MAX_OVERDUE,BUREAU_TOTAL_CREDIT_PROLONG,BUREAU_MAX_CREDIT_PROLONG,BUREAU_MAX_OVERDUE_RECORD_COUNT,BUREAU_ANNUITY_RECORD_COUNT,BUREAU_ACTIVE_LOANS,BUREAU_ACTIVE_TOTAL_CREDIT,BUREAU_ACTIVE_AVG_CREDIT,BUREAU_ACTIVE_TOTAL_DEBT,BUREAU_ACTIVE_AVG_DEBT,BUREAU_ACTIVE_OVERDUE_DAYS_MAX,BUREAU_ACTIVE_OVERDUE_DAYS_MEAN,BUREAU_CREDIT_TYPE_CAR_MORTGAGE_COUNT,BUREAU_CREDIT_TYPE_CONSUMER_COUNT,BUREAU_CREDIT_TYPE_CREDIT_CARD_COUNT,BUREAU_CREDIT_TYPE_OTHER_COUNT,BUREAU_BALANCE_TOTAL_RECORDS,BUREAU_BALANCE_TOTAL_DPD_MONTHS,BUREAU_BALANCE_UNIQUE_CREDITS,BUREAU_BALANCE_MIN_MONTH,BUREAU_BALANCE_MAX_MONTH,BUREAU_BALANCE_DPD_RATIO,PREV_APP_TOTAL_APPLICATIONS,PREV_APP_TOTAL_APPLICATION_AMOUNT,PREV_APP_AVG_APPLICATION_AMOUNT,PREV_APP_MAX_APPLICATION_AMOUNT,PREV_APP_TOTAL_CREDIT,PREV_APP_AVG_CREDIT,PREV_APP_MAX_CREDIT,PREV_APP_AVG_ANNUITY,PREV_APP_MAX_ANNUITY,PREV_APP_AVG_DOWN_PAYMENT,PREV_APP_MAX_DOWN_PAYMENT,PREV_APP_AVG_GOODS_PRICE,PREV_APP_MAX_GOODS_PRICE,PREV_APP_AVG_PAYMENT_COUNT,PREV_APP_MAX_PAYMENT_COUNT,PREV_APP_AVG_DOWN_PAYMENT_RATE,PREV_APP_MAX_DOWN_PAYMENT_RATE,PREV_APP_OLDEST_DECISION,PREV_APP_MOST_RECENT_DECISION,PREV_APP_AVG_DECISION_TIME,PREV_APP_STATUS_APPROVED_COUNT,PREV_APP_STATUS_CANCELED_COUNT,PREV_APP_STATUS_REFUSED_COUNT,PREV_APP_STATUS_UNUSED_OFFER_COUNT,PREV_APP_APPROVAL_RATE,PREV_APP_REFUSAL_RATE,PREV_APP_CONTRACT_CASH_LOANS_COUNT,PREV_APP_CONTRACT_CONSUMER_LOANS_COUNT,PREV_APP_CONTRACT_REVOLVING_LOANS_COUNT,PREV_APP_CLIENT_NEW_COUNT,PREV_APP_CLIENT_REFRESHED_COUNT,PREV_APP_CLIENT_REPEATER_COUNT,PREV_APP_PORTFOLIO_CARDS_COUNT,PREV_APP_PORTFOLIO_CARS_COUNT,PREV_APP_PORTFOLIO_CASH_COUNT,PREV_APP_PORTFOLIO_POS_COUNT,PREV_APP_PRODUCT_WALK_IN_COUNT,PREV_APP_PRODUCT_X_SELL_COUNT,POS_CASH_LOANS,POS_CASH_AVG_LOAN_MONTHS,POS_CASH_MAX_LOAN_MONTHS,POS_CASH_AVG_INST,POS_CASH_AVG_FUTURE_INST,POS_CASH_MAX_DPD,POS_CASH_AVG_DPD,POS_CASH_TOTAL_DPD_MONTHS,POS_CASH_AVG_DPD_RATE,POS_CASH_MAX_DPD_RATE,POS_CASH_MAX_DPD_DEF,POS_CASH_STATUS_ACTIVE_COUNT,POS_CASH_STATUS_AMORTIZED_DEBT_COUNT,POS_CASH_STATUS_COMPLETED_COUNT,POS_CASH_STATUS_DEMAND_COUNT,POS_CASH_STATUS_RETURNED_TO_THE_STORE_COUNT,POS_CASH_STATUS_SIGNED_COUNT,CC_COUNT,CC_AVG_CARD_MONTHS,CC_MAX_CARD_MONTHS,CC_AVG_CARD_BALANCE,CC_MAX_CARD_BALANCE,CC_MAX_CARD_CREDIT_LIMIT,CC_AVG_CARD_UTILIZATION,CC_MAX_CARD_UTILIZATION,CC_TOTAL_CARD_PAYMENTS,CC_AVG_CARD_PAYMENT,CC_AVG_PAYMENT_BALANCE_RATIO,CC_TOTAL_CARD_DRAWINGS,CC_TOTAL_ATM_DRAWINGS,CC_TOTAL_POS_DRAWINGS,CC_TOTAL_OTHER_DRAWINGS,CC_TOTAL_DRAWING_COUNT,CC_TOTAL_ATM_DRAWING_COUNT,CC_TOTAL_POS_DRAWING_COUNT,CC_TOTAL_OTHER_DRAWING_COUNT,CC_MAX_MATURED_INSTALLMENTS,CC_MAX_CARD_DPD,CC_AVG_CARD_DPD,CC_TOTAL_CARD_DPD_MONTHS,CC_AVG_CARD_DPD_RATE,CC_MAX_CARD_DPD_RATE,CC_STATUS_ACTIVE_COUNT,CC_STATUS_APPROVED_COUNT,CC_STATUS_COMPLETED_COUNT,CC_STATUS_DEMAND_COUNT,CC_STATUS_REFUSED_COUNT,CC_STATUS_SENT_PROPOSAL_COUNT,CC_STATUS_SIGNED_COUNT,INSTALL_LOANS,INSTALL_TOTAL_AMOUNT_DUE,INSTALL_TOTAL_AMOUNT_PAID,INSTALL_AVG_PAYMENT_RATIO,INSTALL_AVG_PAYMENT_DELAY,INSTALL_MAX_LATE_PAYMENT_DAYS,INSTALL_TOTAL_LATE_PAYMENTS,INSTALL_AVG_LOAN_LATE_RATE,INSTALL_MAX_LOAN_LATE_RATE,INSTALL_TOTAL_PAYMENT_SHORTFALL,INSTALL_TOTAL_UNDERPAID_INSTALLMENTS,INSTALL_AVG_LOAN_UNDERPAID_RATE,INSTALL_MAX_LOAN_UNDERPAID_RATE,INSTALL_PAYMENT_COMPLETION_RATIO
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.022,0.0198,0.0,0.0,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.00,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,25.920548,1.745205,202500.0,2.007889,0.121978,0.060749,8.0,-1437.0,-103.0,-874.00,0.0,0.0,865055.565,108131.945625,450000.0,245781.0,49156.2,245781.0,0.0,0.0,0.0,0.0,5.0,7.0,2.0,481988.565,240994.2825,245781.0,122890.5,0.0,0.0,0.0,4.0,4.0,0.0,110.0,27.0,8.0,-47.0,0.0,0.245455,1.0,179055.00,179055.00,179055.0,179055.0,179055.00,179055.0,9251.775,9251.775,0.00,0.0,179055.00,179055.0,24.000000,24.0,0.000000,0.000000,-606.0,-606.0,-606.000000,1.0,0.0,0.0,0.0,1.000000,0.000000,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,19.000000,19.0,24.000000,15.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,219625.695,219625.695,1.000000,-20.421053,-12.0,0.0,0.000000,0.0,0.000,0.0,0.000000,0.000000,1.000000
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,45.931507,3.254795,135000.0,4.790750,0.132217,0.027598,4.0,-2586.0,-606.0,-1400.75,0.0,0.0,1017400.500,254350.125000,810000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,1.0,810000.000,810000.0000,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1306309.50,435436.50,900000.0,1452573.0,484191.00,1035882.0,56553.990,98356.995,3442.50,6885.0,435436.50,900000.0,10.000000,12.0,0.050030,0.100061,-2341.0,-746.0,-1305.000000,3.0,0.0,0.0,0.0,1.000000,0.000000,1.0,2.0,0.0,0.0,2.0,1.0,0.0,0.0,1.0,2.0,0.0,1.0,3.0,9.333333,12.0,9.791667,5.666667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1618864.650,1618864.650,1.000000,-7.448413,-1.0,0.0,0.000000,0.0,0.000,0.0,0.000000,0.000000,1.000000
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-4260.0,-2531,26.0,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.555912,0.729567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,52.180822,0.616438,67500.0,2.000000,0.100000,0.050000,2.0,-1326.0,-408.0,-867.00,0.0,0.0,189037.800,94518.900000,94537.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.000,0.0000,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,24282.00,24282.00,24282.0,20106.0,20106.00,20106.0,5357.250,5357.250,4860.00,4860.0,24282.00,24282.0,4.000000,4.0,0.212008,0.212008,-815.0,-815.0,-815.000000,1.0,0.0,0.0,0.0,1.000000,0.000000,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,4.000000,4.0,3.750000,2.250000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,21288.465,21288.465,1.000000,-7.666667,-3.0,0.0,0.000000,0.0,0.000,0.0,0.000000,0.000000,1.000000
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.008019,-9833.0,-2437,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.650442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,2.0,0.0,-617.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,52.068493,8.326027,67500.0,2.316167,0.219900,0.094941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2449829.34,272203.26,688500.0,2625259.5,291695.50,906615.0,23651.175,39954.510,34840.17,66987.0,408304.89,688500.0,23.000000,48.0,0.163412,0.217830,-617.0,-181.0,-272.444444,5.0,3.0,1.0,0.0,0.555556,0.111111,5.0,2.0,2.0,1.0,0.0,8.0,1.0,0.0,3.0,2.0,0.0,4.0,3.0,7.000000,10.0,12.888889,10.214286,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,6.0,6.0,0.0,0.0,270000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1007153.415,1007153.415,1.000000,-25.300000,-1.0,0.0,0.000000,0.0,0.000,0.0,0.000000,0.000000,1.000000
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.028663,-4311.0,-3458,NaN,1,1,0,1,0,0,Core staff,1.0,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,NaN,0.322738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1106.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,54.608219,8.323288,121500.0,4.222222,0.179963,0.042623,1.0,-1149.0,-1149.0,-1149.00,0.0,0.0,146250.000,146250.000000,146250.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.000,0.0000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0,903181.50,150530.25,247500.0,999832.5,166638.75,284400.0,12278.805,22678.785,3390.75,3676.5,150530.25,247500.0,20.666667,48.0,0.159516,0.218890,-2357.0,-374.0,-1222.833333,6.0,0.0,0.0,0.0,1.000000,0.000000,4.0,2.0,0.0,1.0,0.0,5.0,0.0,0.0,4.0,2.0,1.0,3.0,5.0,13.200000,18.0,15.066667,8.966667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,835985.340,806127.975,0.956103,-2.887220,12.0,16.0,0.287912,1.0,29857.365,6.0,0.087912,0.285714,0.964285

### **Light validation**

In [13]:
print("Shape:", df.shape)
print("-"*100)
print("Duplicate rows:", df.duplicated().sum())
print("-"*100)
print("Duplicate SK_ID_CURR:", df['SK_ID_CURR'].duplicated().sum())
print("-"*100)
print("Target distribution:")
print("-"*100)
print(df['TARGET'].value_counts())
print("-"*100)
print(df['TARGET'].value_counts(normalize=True))

Shape: (307507, 262)
----------------------------------------------------------------------------------------------------
Duplicate rows: 0
----------------------------------------------------------------------------------------------------
Duplicate SK_ID_CURR: 0
----------------------------------------------------------------------------------------------------
Target distribution:
----------------------------------------------------------------------------------------------------
TARGET
0    282682
1     24825
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
TARGET
0    0.91927
1    0.08073
Name: proportion, dtype: float64

**MISSING VALUES**

In [14]:
df.isna().sum().sort_values(ascending=False).head()

CC_AVG_CARD_DPD_RATE           220602
CC_TOTAL_CARD_DPD_MONTHS       220602
CC_AVG_CARD_DPD                220602
CC_MAX_CARD_DPD                220602
CC_MAX_MATURED_INSTALLMENTS    220602
dtype: int64

In [15]:
missing_pct = (
    df.isna()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

missing_pct.head(20)

CC_AVG_CARD_DPD_RATE            71.738855
CC_TOTAL_CARD_DPD_MONTHS        71.738855
CC_AVG_CARD_DPD                 71.738855
CC_MAX_CARD_DPD                 71.738855
CC_MAX_MATURED_INSTALLMENTS     71.738855
CC_TOTAL_OTHER_DRAWING_COUNT    71.738855
CC_TOTAL_POS_DRAWING_COUNT      71.738855
CC_TOTAL_ATM_DRAWING_COUNT      71.738855
CC_TOTAL_DRAWING_COUNT          71.738855
CC_TOTAL_OTHER_DRAWINGS         71.738855
CC_TOTAL_POS_DRAWINGS           71.738855
CC_TOTAL_ATM_DRAWINGS           71.738855
CC_TOTAL_CARD_DRAWINGS          71.738855
CC_AVG_PAYMENT_BALANCE_RATIO    71.738855
CC_AVG_CARD_PAYMENT             71.738855
CC_TOTAL_CARD_PAYMENTS          71.738855
CC_AVG_CARD_MONTHS              71.738855
CC_COUNT                        71.738855
CC_AVG_CARD_BALANCE             71.738855
CC_AVG_CARD_UTILIZATION         71.738855
dtype: float64

In [16]:
# check constant columns
X_temp = df.drop(columns=['SK_ID_CURR', 'TARGET'])

constant_cols = [
    col for col in X_temp.columns
    if X_temp[col].nunique(dropna=False) <= 1
]

print("Constant columns:", constant_cols)
print("Number of constant columns:", len(constant_cols))

Constant columns: []
Number of constant columns: 0

### **Separate features and target**

In [17]:
X = df.drop(columns=['SK_ID_CURR', 'TARGET'])
y = df['TARGET']

### **Train / Val / Test Split**
* 70% / 15% / 15%.

In [18]:
# First: separate 15% test set
X_temp, X_test, y_temp, y_test = train_test_split(
    X,
    y,
    test_size=0.15,
    random_state=42,
    stratify=y
)

# Second: take 15% of the original data as validation
# Since X_temp is 85% of the original data:
# 15 / 85 = 0.17647
X_train, X_val, y_train, y_val = train_test_split(
    X_temp,
    y_temp,
    test_size=15/85,
    random_state=42,
    stratify=y_temp
)

print("Train:", X_train.shape, "Default rate:", y_train.mean())
print("Val:  ", X_val.shape,   "Default rate:", y_val.mean())
print("Test: ", X_test.shape,  "Default rate:", y_test.mean())

Train: (215254, 260) Default rate: 0.08072788426695904
Val:   (46126, 260) Default rate: 0.08073537701079651
Test:  (46127, 260) Default rate: 0.08073362672621241

In [19]:
# Numerical & Categorical columns

num_features = X_train.select_dtypes(
    include=['int64', 'float64']
).columns.tolist()

cat_features = X_train.select_dtypes(
    include=['object', 'category']
).columns.tolist()

print("Numerical features:", len(num_features))
print("Categorical features:", len(cat_features))

Numerical features: 244
Categorical features: 16

In [20]:
# Preprocessing Pipeline

numeric_transformer = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='median'))
    ]
)

categorical_transformer = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('encoder', OneHotEncoder(
            handle_unknown='ignore',
            drop='first',
            sparse_output=False
        ))
    ]
)

preprocessor = ColumnTransformer([
    ('num', numeric_transformer, num_features),
    ('cat', categorical_transformer, cat_features)
])

For this baseline, median imputation is fine. We can make the historical missingness treatment more sophisticated after we see baseline performance.

### **Baseline Models**

In [21]:
# Define the four models

models = {
    'Random Forest': RandomForestClassifier(
        n_estimators=100,
        random_state=42,
        class_weight='balanced',
        n_jobs=-1
    ),

    'XGBoost': XGBClassifier(
        n_estimators=100,
        random_state=42,
        eval_metric='logloss',
        n_jobs=-1
    ),

    'LightGBM': LGBMClassifier(
        n_estimators=100,
        random_state=42,
        verbosity=-1,
        n_jobs=-1
    )
}

In [22]:
trained_models = {}

results = []

for name, model in models.items():

    print(f"Training {name}...")

    # Create pipeline
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('model', model)
    ])

    # Train
    pipeline.fit(X_train, y_train)

    trained_models[name] = pipeline

    # Predictions
    y_pred = pipeline.predict(X_val)
    y_prob = pipeline.predict_proba(X_val)[:, 1]

    # Evaluation
    results.append({
        'Model': name,
        'ROC-AUC': roc_auc_score(y_val, y_prob),
        'Recall': recall_score(y_val, y_pred),
        'Precision': precision_score(y_val, y_pred),
        'F1-Score': f1_score(y_val, y_pred)
    })

results_df = (
    pd.DataFrame(results)
    .sort_values('ROC-AUC', ascending=False)
    .reset_index(drop=True)
)

display(results_df)

Training Random Forest...
Training XGBoost...
Training LightGBM...

           Model   ROC-AUC    Recall  Precision  F1-Score
0       LightGBM  0.784547  0.040279   0.555556  0.075113
1        XGBoost  0.769887  0.066058   0.470363  0.115846
2  Random Forest  0.741291  0.002148   0.363636  0.004271

### **Feature Gain**

**Step 1 — Get the trained LightGBM pipeline**

In [23]:

lightgbm_pipeline = trained_models['LightGBM']

lightgbm_model = lightgbm_pipeline['model']
preprocessor_fitted = lightgbm_pipeline['preprocessor']

**Step 2 — Get the transformed feature names**

In [24]:

feature_names = preprocessor_fitted.get_feature_names_out()

print("Number of transformed features:", len(feature_names))
print(feature_names[:10])

Number of transformed features: 367
['num__CNT_CHILDREN' 'num__AMT_INCOME_TOTAL' 'num__AMT_CREDIT'
 'num__AMT_ANNUITY' 'num__AMT_GOODS_PRICE'
 'num__REGION_POPULATION_RELATIVE' 'num__DAYS_REGISTRATION'
 'num__DAYS_ID_PUBLISH' 'num__OWN_CAR_AGE' 'num__FLAG_MOBIL']

**Step 3 — Calculate LightGBM Gain**

In [25]:

gain_values = lightgbm_model.booster_.feature_importance(
    importance_type='gain'
)

gain_df = pd.DataFrame({
    'Feature': feature_names,
    'Gain': gain_values
})

gain_df = (
    gain_df
    .sort_values('Gain', ascending=False)
    .reset_index(drop=True)
)

gain_df['Gain_percentage'] = (
    gain_df['Gain'] / gain_df['Gain'].sum()
) * 100

In [26]:
print("Shape", gain_df.shape)
gain_df.head(100)

Shape (367, 3)

,Feature,Gain,Gain_percentage
0,num__EXT_SOURCE_2,24140.187907,18.061509
1,num__EXT_SOURCE_3,23294.643782,17.428879
2,num__EXT_SOURCE_1,7196.996310,5.384739
3,num__ANNUITY_CREDIT_RATIO,5346.998801,4.000585
4,num__AGE,3199.928031,2.394162
5,num__POS_CASH_AVG_FUTURE_INST,3142.508003,2.351201
6,num__INSTALL_AVG_LOAN_LATE_RATE,3059.248718,2.288907
7,num__YEARS_EMPLOYED,2968.013835,2.220646
8,cat__CODE_GENDER_M,2315.676820,1.732572
9,num__AMT_ANNUITY,2105.719740,1.575484
10,num__INSTALL_TOTAL_AMOUNT_PAID,2047.672416,1.532053
11,num__PREV_APP_REFUSAL_RATE,2040.995981,1.527058
12,num__CC_AVG_CARD_UTILIZATION,1906.686507,1.426569
13,num__AMT_CREDIT,1665.080450,1.245801
14,num__AMT_GOODS_PRICE,1510.727015,1.130315
15,num__BUREAU_AVG_DEBT,1406.162200,1.052080
16,cat__NAME_EDUCATION_TYPE_Higher education,1336.912212,1.000268
17,num__PREV_APP_MAX_DOWN_PAYMENT,1308.166002,0.978760
18,num__BUREAU_DAYS_CREDIT_MAX,1232.717993,0.922310
19,num__DAYS_ID_PUBLISH,1091.921688,0.816968
20,num__BUREAU_DAYS_CREDIT_MEAN,1049.427094,0.785174
21,num__INSTALL_PAYMENT_COMPLETION_RATIO,987.293181,0.738685
22,num__ANNUITY_INCOME_RATIO,864.924097,0.647130
23,num__BUREAU_ACTIVE_LOANS,806.145400,0.603152
24,num__INSTALL_AVG_LOAN_UNDERPAID_RATE,785.424400,0.587649
25,num__PREV_APP_OLDEST_DECISION,762.693708,0.570642
26,num__CC_MAX_CARD_UTILIZATION,711.512699,0.532349
27,num__FLAG_DOCUMENT_3,699.064501,0.523035
28,num__PREV_APP_MAX_PAYMENT_COUNT,689.262806,0.515701
29,num__POS_CASH_MAX_DPD_DEF,677.887195,0.507190
30,num__BUREAU_AVG_CREDIT,669.857000,0.501182
31,num__CC_MAX_CARD_BALANCE,659.858501,0.493701
32,num__INSTALL_TOTAL_AMOUNT_DUE,656.946404,0.491522
33,num__DAYS_REGISTRATION,652.115460,0.487908
34,num__CC_AVG_CARD_BALANCE,635.298596,0.475326
35,num__PREV_APP_APPROVAL_RATE,635.076807,0.475160
36,num__POS_CASH_LOANS,627.858499,0.469759
37,num__POS_CASH_AVG_LOAN_MONTHS,625.521007,0.468010
38,num__OWN_CAR_AGE,619.508297,0.463511
39,cat__FLAG_OWN_CAR_Y,618.234894,0.462559
40,cat__NAME_EDUCATION_TYPE_Secondary / secondary...,597.292099,0.446890
41,num__CREDIT_INCOME_RATIO,591.449103,0.442518
42,num__PREV_APP_MAX_DOWN_PAYMENT_RATE,591.391605,0.442475
43,num__INSTALL_MAX_LATE_PAYMENT_DAYS,588.429004,0.440258
44,cat__NAME_FAMILY_STATUS_Married,582.400785,0.435748
45,num__PREV_APP_AVG_ANNUITY,528.901999,0.395721
46,num__BUREAU_TOTAL_CREDIT,524.895506,0.392723
47,num__REGION_RATING_CLIENT_W_CITY,492.107601,0.368191
48,num__PREV_APP_AVG_DECISION_TIME,453.759398,0.339499
49,num__BUREAU_ACTIVE_TOTAL_CREDIT,418.252403,0.312933
50,num__BUREAU_MAX_CREDIT,412.347204,0.308515
51,num__PREV_APP_MOST_RECENT_DECISION,410.618398,0.307222
52,num__CC_TOTAL_DRAWING_COUNT,393.285302,0.294253
53,num__INSTALL_AVG_PAYMENT_DELAY,384.454799,0.287646
54,num__CC_AVG_CARD_MONTHS,360.359004,0.269618
55,num__PREV_APP_AVG_PAYMENT_COUNT,356.974902,0.267086
56,num__PREV_APP_AVG_DOWN_PAYMENT,356.613497,0.266816
57,num__INSTALL_AVG_PAYMENT_RATIO,354.658698,0.265353
58,num__CC_TOTAL_ATM_DRAWING_COUNT,335.300445,0.250869
59,num__REGION_POPULATION_RELATIVE,333.935321,0.249848
60,num__BUREAU_DAYS_CREDIT_MIN,324.960799,0.243133
61,num__REG_CITY_NOT_LIVE_CITY,322.672801,0.241421
62,num__PREV_APP_PRODUCT_WALK_IN_COUNT,317.945700,0.237885
63,num__BUREAU_BALANCE_TOTAL_RECORDS,315.054624,0.235722
64,num__TOTALAREA_MODE,310.319603,0.232179
65,num__POS_CASH_MAX_LOAN_MONTHS,308.033999,0.230469
66,num__DEF_60_CNT_SOCIAL_CIRCLE,307.698597,0.230218
67,cat__NAME_CONTRACT_TYPE_Revolving loans,305.412199,0.228507
68,num__CC_TOTAL_ATM_DRAWINGS,299.333200,0.223959
69,num__DAYS_LAST_PHONE_CHANGE,291.165601,0.217848
70,num__BUREAU_TOTAL_OVERDUE,290.077817,0.217034
71,num__BUREAU_ACTIVE_AVG_CREDIT,281.815299,0.210852
72,num__BUREAU_CREDIT_TYPE_CAR_MORTGAGE_COUNT,279.132100,0.208845
73,num__INCOME_PER_FAMILY_MEMBER,258.024899,0.193052
74,num__BUREAU_ACTIVE_TOTAL_DEBT,256.041703,0.191568
75,num__PREV_APP_AVG_DOWN_PAYMENT_RATE,250.113499,0.187133
76,num__CC_MAX_MATURED_INSTALLMENTS,242.469301,0.181414
77,num__CC_TOTAL_CARD_PAYMENTS,241.043098,0.180347
78,num__BUREAU_TOTAL_DEBT,239.657301,0.179310
79,num__PREV_APP_MAX_CREDIT,237.895201,0.177991
80,num__PREV_APP_AVG_CREDIT,234.183299,0.175214
81,num__BUREAU_CREDIT_TYPE_CONSUMER_COUNT,230.953699,0.172798
82,num__INSTALL_TOTAL_PAYMENT_SHORTFALL,226.086201,0.169156
83,num__HOUR_APPR_PROCESS_START,223.642299,0.167328
84,cat__NAME_INCOME_TYPE_Working,223.435301,0.167173
85,num__INSTALL_MAX_LOAN_LATE_RATE,222.337500,0.166351
86,num__BUREAU_CREDIT_TYPE_OTHER_COUNT,222.300197,0.166323
87,num__DEF_30_CNT_SOCIAL_CIRCLE,218.045400,0.163140
88,num__BUREAU_MAX_DEBT,201.103498,0.150464
89,num__BUREAU_ACTIVE_AVG_DEBT,200.057801,0.149682
90,num__PREV_APP_AVG_APPLICATION_AMOUNT,194.395802,0.145445
91,num__PREV_APP_STATUS_APPROVED_COUNT,190.601702,0.142607
92,num__BUREAU_MAX_OVERDUE,188.673401,0.141164
93,num__YEARS_BEGINEXPLUATATION_MODE,188.206300,0.140815
94,num__POS_CASH_AVG_INST,180.510801,0.135057
95,num__PREV_APP_MAX_APPLICATION_AMOUNT,179.306998,0.134156
96,num__PREV_APP_AVG_GOODS_PRICE,176.955898,0.132397
97,num__AMT_REQ_CREDIT_BUREAU_QRT,174.060011,0.130230
98,cat__OCCUPATION_TYPE_Core staff,171.058500,0.127985
99,num__AMT_INCOME_TOTAL,163.218901,0.122119

**Step 4 — Calculate split importance too**

In [27]:
split_values = lightgbm_model.booster_.feature_importance(
    importance_type='split'
)

split_df = pd.DataFrame({
    'Feature': feature_names,
    'Split': split_values
})

split_df = (
    split_df
    .sort_values('Split', ascending=False)
    .reset_index(drop=True)
)

In [28]:
print("Shape", split_df.shape)
split_df.head(100)

Shape (367, 2)

                                              Feature  Split
0                                   num__EXT_SOURCE_1    135
1                           num__ANNUITY_CREDIT_RATIO    124
2                                   num__EXT_SOURCE_2    102
3                                   num__EXT_SOURCE_3     97
4                                            num__AGE     92
5                       num__POS_CASH_AVG_FUTURE_INST     84
6                                    num__AMT_ANNUITY     65
7                     num__INSTALL_AVG_LOAN_LATE_RATE     64
8                                 num__YEARS_EMPLOYED     57
9                      num__INSTALL_TOTAL_AMOUNT_PAID     55
10                                    num__AMT_CREDIT     54
11                        num__BUREAU_DAYS_CREDIT_MAX     51
12                               num__DAYS_ID_PUBLISH     49
13                               num__BUREAU_AVG_DEBT     41
14                               num__AMT_GOODS_PRICE     40
15                             num__DAYS_REGISTRATION     40
16                          num__ANNUITY_INCOME_RATIO     36
17                         num__PREV_APP_REFUSAL_RATE     35
18                       num__CC_AVG_CARD_UTILIZATION     35
19                           num__BUREAU_ACTIVE_LOANS     34
20                                 cat__CODE_GENDER_M     31
21                     num__PREV_APP_MAX_DOWN_PAYMENT     31
22              num__INSTALL_PAYMENT_COMPLETION_RATIO     31
23                           num__CC_MAX_CARD_BALANCE     30
24                       num__BUREAU_DAYS_CREDIT_MEAN     28
25                      num__POS_CASH_AVG_LOAN_MONTHS     28
26                 num__INSTALL_MAX_LATE_PAYMENT_DAYS     27
27                    num__PREV_APP_MAX_PAYMENT_COUNT     27
28                             num__BUREAU_AVG_CREDIT     27
29                          num__PREV_APP_AVG_ANNUITY     26
30                          num__POS_CASH_MAX_DPD_DEF     26
31                      num__PREV_APP_OLDEST_DECISION     25
32                      num__INSTALL_TOTAL_AMOUNT_DUE     24
33                num__PREV_APP_MAX_DOWN_PAYMENT_RATE     23
34                    num__PREV_APP_AVG_DECISION_TIME     22
35                           num__BUREAU_TOTAL_CREDIT     22
36                 num__PREV_APP_MOST_RECENT_DECISION     22
37                           num__CREDIT_INCOME_RATIO     21
38                       num__CC_MAX_CARD_UTILIZATION     21
39                     num__INSTALL_AVG_PAYMENT_DELAY     21
40                    cat__NAME_FAMILY_STATUS_Married     20
41                        num__CC_TOTAL_DRAWING_COUNT     19
42                                   num__OWN_CAR_AGE     19
43                    num__BUREAU_ACTIVE_TOTAL_CREDIT     19
44                             num__BUREAU_MAX_CREDIT     19
45                   num__REGION_RATING_CLIENT_W_CITY     18
46                        num__DAYS_LAST_PHONE_CHANGE     18
47                    num__REGION_POPULATION_RELATIVE     18
48                  num__BUREAU_BALANCE_TOTAL_RECORDS     18
49               num__INSTALL_AVG_LOAN_UNDERPAID_RATE     18
50                                cat__FLAG_OWN_CAR_Y     17
51                           num__CC_AVG_CARD_BALANCE     17
52          cat__NAME_EDUCATION_TYPE_Higher education     17
53                        num__BUREAU_DAYS_CREDIT_MIN     17
54                    num__PREV_APP_AVG_PAYMENT_COUNT     16
55                     num__PREV_APP_AVG_DOWN_PAYMENT     15
56                      num__INCOME_PER_FAMILY_MEMBER     15
57                         num__CC_TOTAL_ATM_DRAWINGS     15
58                      num__POS_CASH_MAX_LOAN_MONTHS     15
59                      num__BUREAU_ACTIVE_AVG_CREDIT     14
60                    num__CC_TOTAL_ATM_DRAWING_COUNT     14
61                        num__PREV_APP_APPROVAL_RATE     14
62                                num__TOTALAREA_MODE     13
63                        num__CC_TOTAL_CARD_PAYMENTS     12
64                           num__PREV_APP_AVG_CREDIT     12
65                                num__POS_CASH_LOANS     12
66                          num__BUREAU_TOTAL_OVERDUE     12
67               num__INSTALL_TOTAL_PAYMENT_SHORTFALL     12
68                     num__INSTALL_AVG_PAYMENT_RATIO     12
69                             num__BUREAU_TOTAL_DEBT     11
70                      num__BUREAU_ACTIVE_TOTAL_DEBT     11
71                   num__CC_MAX_MATURED_INSTALLMENTS     11
72            cat__NAME_CONTRACT_TYPE_Revolving loans     11
73                num__PREV_APP_AVG_DOWN_PAYMENT_RATE     11
74                            num__CC_AVG_CARD_MONTHS     11
75                           num__PREV_APP_MAX_CREDIT     11
76             num__BUREAU_CREDIT_TYPE_CONSUMER_COUNT     11
77                               num__BUREAU_MAX_DEBT     10
78                      num__DEF_30_CNT_SOCIAL_CIRCLE     10
79                        num__BUREAU_ACTIVE_AVG_DEBT     10
80                num__BUREAU_CREDIT_TYPE_OTHER_COUNT     10
81               num__PREV_APP_AVG_APPLICATION_AMOUNT     10
82                      num__DEF_60_CNT_SOCIAL_CIRCLE     10
83                       num__HOUR_APPR_PROCESS_START     10
84                        num__REG_CITY_NOT_LIVE_CITY     10
85  cat__NAME_EDUCATION_TYPE_Secondary / secondary...     10
86                num__PREV_APP_PRODUCT_WALK_IN_COUNT      9
87                      num__PREV_APP_AVG_GOODS_PRICE      9
88                    num__INSTALL_MAX_LOAN_LATE_RATE      9
89                  num__YEARS_BEGINEXPLUATATION_MEDI      9
90                  num__YEARS_BEGINEXPLUATATION_MODE      9
91                     num__AMT_REQ_CREDIT_BUREAU_QRT      9
92                              num__AMT_INCOME_TOTAL      9
93                               num__FLAG_DOCUMENT_3      9
94         num__BUREAU_CREDIT_TYPE_CAR_MORTGAGE_COUNT      9
95               num__PREV_APP_MAX_APPLICATION_AMOUNT      9
96                cat__ORGANIZATION_TYPE_Construction      8
97                     num__CC_STATUS_COMPLETED_COUNT      8
98                                num__COMMONAREA_AVG      8
99                             num__POS_CASH_AVG_INST      8

**Step 5 — Put Gain and Split together**

In [29]:
importance_compare = pd.DataFrame({
    'Feature': gain_df['Feature'],
    'Gain': gain_df['Gain'],
    'Gain_percentage': gain_df['Gain_percentage'],
    'Split': split_df['Split']
})

importance_compare = (
    importance_compare
    .sort_values('Gain',ascending=False)
    .reset_index(drop=True)
)

In [30]:
importance_compare.head()

                     Feature          Gain  Gain_percentage  Split
0          num__EXT_SOURCE_2  24140.187907        18.061509    135
1          num__EXT_SOURCE_3  23294.643782        17.428879    124
2          num__EXT_SOURCE_1   7196.996310         5.384739    102
3  num__ANNUITY_CREDIT_RATIO   5346.998801         4.000585     97
4                   num__AGE   3199.928031         2.394162     92

**Step 6 — Find zero-Gain features**

In [31]:
zero_gain_features = gain_df[
    gain_df['Gain'] == 0
]['Feature'].tolist()

print("Zero-Gain Features:", len(zero_gain_features))

Zero-Gain Features: 129

**Step 7 — Now do correlation redundancy**

In [32]:
corr_matrix = X_train[num_features].corr().abs()

In [33]:
upper = corr_matrix.where(
    np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
)

In [34]:
high_corr_pairs = (
    upper
    .stack()
    .reset_index()
)

high_corr_pairs.columns = [
    'Feature_1',
    'Feature_2',
    'Correlation'
]

high_corr_pairs = (
    high_corr_pairs[
        high_corr_pairs['Correlation'] >= 0.90
    ]
    .sort_values('Correlation', ascending=False)
    .reset_index(drop=True)
)

In [35]:
high_corr_pairs.shape

(95, 3)

In [36]:
high_corr_pairs.head()

                         Feature_1                      Feature_2  Correlation
0  PREV_APP_MAX_APPLICATION_AMOUNT       PREV_APP_MAX_GOODS_PRICE     0.999959
1           BUREAU_DAYS_CREDIT_MIN       BUREAU_BALANCE_MIN_MONTH     0.999915
2               BUREAU_TOTAL_LOANS  BUREAU_BALANCE_UNIQUE_CREDITS     0.999861
3                  CC_MAX_CARD_DPD                CC_AVG_CARD_DPD     0.999329
4             CC_AVG_CARD_DPD_RATE           CC_MAX_CARD_DPD_RATE     0.999301

**Step 8 — Create a function to recover the original column**

In [37]:
def get_original_feature(feature_name, categorical_columns):

    # Numerical feature
    if feature_name.startswith('num__'):
        return feature_name.replace('num__', '', 1)

    # Categorical feature
    if feature_name.startswith('cat__'):
        encoded_name = feature_name.replace('cat__', '', 1)

        for col in categorical_columns:
            if encoded_name.startswith(col + '_'):
                return col

        return encoded_name

    return feature_name

**Step 9 — Apply the function**

In [38]:
gain_df['Original_Feature'] = gain_df['Feature'].apply(
    lambda x: get_original_feature(x, cat_features)
)

In [39]:
gain_df.head(2)

             Feature          Gain  Gain_percentage Original_Feature
0  num__EXT_SOURCE_2  24140.187907        18.061509     EXT_SOURCE_2
1  num__EXT_SOURCE_3  23294.643782        17.428879     EXT_SOURCE_3

**Step 10 — ['original_gain'] =  Group by original feature and sum the Gain**

In [40]:
original_gain = (
    gain_df
    .groupby('Original_Feature', as_index=False)['Gain']
    .sum()
    .sort_values('Gain', ascending=False)
    .reset_index(drop=True)
)

**Step 11 — Add Gain percentage at original-column level**

In [41]:
original_gain['Gain_percentage'] = (
    original_gain['Gain'] /
    original_gain['Gain'].sum()
) * 100

In [42]:
print("ORIGNAL GAIN SHAPE : ",original_gain.shape)
original_gain.head(2)

ORIGNAL GAIN SHAPE :  (260, 3)

  Original_Feature          Gain  Gain_percentage
0     EXT_SOURCE_2  24140.187907        18.061509
1     EXT_SOURCE_3  23294.643782        17.428879

**Step 12 — Compare the original Gain with your correlation table**

In [43]:
gain_lookup = (
    original_gain
    .set_index('Original_Feature')['Gain']
    .to_dict()
)

**Step 13 — Add Gain of Feature 1 and Feature 2**

In [44]:
high_corr_pairs['Gain_1'] = (
    high_corr_pairs['Feature_1']
    .map(gain_lookup)
)

high_corr_pairs['Gain_2'] = (
    high_corr_pairs['Feature_2']
    .map(gain_lookup)
)

**Step 14 — Automatically suggest which correlated feature is weaker**

In [45]:
high_corr_pairs['Keep'] = np.where(
    high_corr_pairs['Gain_1'] >= high_corr_pairs['Gain_2'],
    high_corr_pairs['Feature_1'],
    high_corr_pairs['Feature_2']
)

high_corr_pairs['Suggested_Remove'] = np.where(
    high_corr_pairs['Gain_1'] >= high_corr_pairs['Gain_2'],
    high_corr_pairs['Feature_2'],
    high_corr_pairs['Feature_1']
)

In [46]:
print("SHAPE: ",high_corr_pairs.shape)
high_corr_pairs.head()

SHAPE:  (95, 7)

,Feature_1,Feature_2,Correlation,Gain_1,Gain_2,Keep,Suggested_Remove
0,PREV_APP_MAX_APPLICATION_AMOUNT,PREV_APP_MAX_GOODS_PRICE,0.999959,179.306998,16.854300,PREV_APP_MAX_APPLICATION_AMOUNT,PREV_APP_MAX_GOODS_PRICE
1,BUREAU_DAYS_CREDIT_MIN,BUREAU_BALANCE_MIN_MONTH,0.999915,324.960799,113.003209,BUREAU_DAYS_CREDIT_MIN,BUREAU_BALANCE_MIN_MONTH
2,BUREAU_TOTAL_LOANS,BUREAU_BALANCE_UNIQUE_CREDITS,0.999861,72.643200,16.657101,BUREAU_TOTAL_LOANS,BUREAU_BALANCE_UNIQUE_CREDITS
3,CC_MAX_CARD_DPD,CC_AVG_CARD_DPD,0.999329,57.882299,29.073701,CC_MAX_CARD_DPD,CC_AVG_CARD_DPD
4,CC_AVG_CARD_DPD_RATE,CC_MAX_CARD_DPD_RATE,0.999301,41.900002,33.618100,CC_AVG_CARD_DPD_RATE,CC_MAX_CARD_DPD_RATE

### **REMOVING THE FEATURE**

**Step 1 — Find original columns with zero total Gain**

In [47]:
zero_gain_original = original_gain[
    original_gain['Gain'] == 0
].copy()


print(
    "Original columns with zero total Gain:",
    len(zero_gain_original)
)

zero_gain_original.head(60)

Original columns with zero total Gain: 52

                                Original_Feature  Gain  Gain_percentage
208                      CC_TOTAL_OTHER_DRAWINGS   0.0              0.0
209                                 CNT_CHILDREN   0.0              0.0
210                                ELEVATORS_AVG   0.0              0.0
211                               ELEVATORS_MEDI   0.0              0.0
212                CC_STATUS_SENT_PROPOSAL_COUNT   0.0              0.0
213                      CC_STATUS_REFUSED_COUNT   0.0              0.0
214                       CC_STATUS_SIGNED_COUNT   0.0              0.0
215                 CC_TOTAL_OTHER_DRAWING_COUNT   0.0              0.0
216                     CC_STATUS_APPROVED_COUNT   0.0              0.0
217                       CC_STATUS_DEMAND_COUNT   0.0              0.0
218                              YEARS_BUILD_AVG   0.0              0.0
219                                     CC_COUNT   0.0              0.0
220                       REG_CITY_NOT_WORK_CITY   0.0              0.0
221                   AMT_REQ_CREDIT_BUREAU_HOUR   0.0              0.0
222                   AMT_REQ_CREDIT_BUREAU_WEEK   0.0              0.0
223                         REGION_RATING_CLIENT   0.0              0.0
224                   REG_REGION_NOT_LIVE_REGION   0.0              0.0
225                    BUREAU_MAX_CREDIT_PROLONG   0.0              0.0
226                      BUREAU_OVERDUE_DAYS_MAX   0.0              0.0
227                  BUREAU_TOTAL_CREDIT_PROLONG   0.0              0.0
228                              FLAG_DOCUMENT_2   0.0              0.0
229                             FLAG_DOCUMENT_19   0.0              0.0
230                             FLAG_DOCUMENT_17   0.0              0.0
231                             FLAG_DOCUMENT_15   0.0              0.0
232                             FLAG_DOCUMENT_13   0.0              0.0
233                             FLAG_DOCUMENT_14   0.0              0.0
234                             FLAG_DOCUMENT_11   0.0              0.0
235                             FLAG_DOCUMENT_12   0.0              0.0
236                             FLAG_DOCUMENT_10   0.0              0.0
237                           NONLIVINGAREA_MEDI   0.0              0.0
238                               FLAG_EMP_PHONE   0.0              0.0
239                                   FLAG_MOBIL   0.0              0.0
240                              FLAG_DOCUMENT_9   0.0              0.0
241                           FONDKAPREMONT_MODE   0.0              0.0
242                               FLOORSMIN_MEDI   0.0              0.0
243                               FLOORSMIN_MODE   0.0              0.0
244                                   FLAG_EMAIL   0.0              0.0
245                     NONLIVINGAPARTMENTS_MEDI   0.0              0.0
246                      LIVE_CITY_NOT_WORK_CITY   0.0              0.0
247                  LIVE_REGION_NOT_WORK_REGION   0.0              0.0
248                              FLAG_OWN_REALTY   0.0              0.0
249                              FLAG_DOCUMENT_5   0.0              0.0
250                              FLAG_DOCUMENT_7   0.0              0.0
251                              FLAG_DOCUMENT_8   0.0              0.0
252                             FLAG_DOCUMENT_20   0.0              0.0
253                              FLAG_DOCUMENT_4   0.0              0.0
254         POS_CASH_STATUS_AMORTIZED_DEBT_COUNT   0.0              0.0
255                 POS_CASH_STATUS_DEMAND_COUNT   0.0              0.0
256               PREV_APP_CLIENT_REPEATER_COUNT   0.0              0.0
257  POS_CASH_STATUS_RETURNED_TO_THE_STORE_COUNT   0.0              0.0
258                PREV_APP_PORTFOLIO_CARS_COUNT   0.0              0.0
259           PREV_APP_STATUS_UNUSED_OFFER_COUNT   0.0              0.0

**Step 2 — Create the ≥0.95 correlation dataframe**

In [48]:
very_high_corr = high_corr_pairs[
    high_corr_pairs['Correlation'] >= 0.95
].copy()

print("Highly correlated pairs:", len(very_high_corr))

Highly correlated pairs: 67

In [49]:
very_high_corr.sort_values(
    'Correlation', ascending=False
).head(70)

,Feature_1,Feature_2,Correlation,Gain_1,Gain_2,Keep,Suggested_Remove
0,PREV_APP_MAX_APPLICATION_AMOUNT,PREV_APP_MAX_GOODS_PRICE,0.999959,179.306998,16.854300,PREV_APP_MAX_APPLICATION_AMOUNT,PREV_APP_MAX_GOODS_PRICE
1,BUREAU_DAYS_CREDIT_MIN,BUREAU_BALANCE_MIN_MONTH,0.999915,324.960799,113.003209,BUREAU_DAYS_CREDIT_MIN,BUREAU_BALANCE_MIN_MONTH
2,BUREAU_TOTAL_LOANS,BUREAU_BALANCE_UNIQUE_CREDITS,0.999861,72.643200,16.657101,BUREAU_TOTAL_LOANS,BUREAU_BALANCE_UNIQUE_CREDITS
3,CC_MAX_CARD_DPD,CC_AVG_CARD_DPD,0.999329,57.882299,29.073701,CC_MAX_CARD_DPD,CC_AVG_CARD_DPD
4,CC_AVG_CARD_DPD_RATE,CC_MAX_CARD_DPD_RATE,0.999301,41.900002,33.618100,CC_AVG_CARD_DPD_RATE,CC_MAX_CARD_DPD_RATE
5,YEARS_BUILD_AVG,YEARS_BUILD_MEDI,0.998428,0.000000,27.010800,YEARS_BUILD_MEDI,YEARS_BUILD_AVG
6,OBS_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,0.998386,110.596599,87.588699,OBS_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE
7,FLOORSMIN_AVG,FLOORSMIN_MEDI,0.997187,82.471300,0.000000,FLOORSMIN_AVG,FLOORSMIN_MEDI
8,CC_AVG_CARD_MONTHS,CC_MAX_CARD_MONTHS,0.997173,360.359004,89.832699,CC_AVG_CARD_MONTHS,CC_MAX_CARD_MONTHS
9,FLOORSMAX_AVG,FLOORSMAX_MEDI,0.997022,47.337698,32.916800,FLOORSMAX_AVG,FLOORSMAX_MEDI
10,ENTRANCES_AVG,ENTRANCES_MEDI,0.996825,21.841499,27.113600,ENTRANCES_MEDI,ENTRANCES_AVG
11,COMMONAREA_AVG,COMMONAREA_MEDI,0.996249,133.102001,26.978300,COMMONAREA_AVG,COMMONAREA_MEDI
12,LIVINGAREA_AVG,LIVINGAREA_MEDI,0.995852,109.191603,128.879801,LIVINGAREA_MEDI,LIVINGAREA_AVG
13,ELEVATORS_AVG,ELEVATORS_MEDI,0.995826,0.000000,0.000000,ELEVATORS_AVG,ELEVATORS_MEDI
14,BUREAU_TOTAL_DEBT,BUREAU_ACTIVE_TOTAL_DEBT,0.994951,239.657301,256.041703,BUREAU_ACTIVE_TOTAL_DEBT,BUREAU_TOTAL_DEBT
15,APARTMENTS_AVG,APARTMENTS_MEDI,0.994445,103.174300,61.181400,APARTMENTS_AVG,APARTMENTS_MEDI
16,YEARS_BEGINEXPLUATATION_AVG,YEARS_BEGINEXPLUATATION_MEDI,0.994424,160.842999,140.387750,YEARS_BEGINEXPLUATATION_AVG,YEARS_BEGINEXPLUATATION_MEDI
17,BASEMENTAREA_AVG,BASEMENTAREA_MEDI,0.993976,114.965002,43.733500,BASEMENTAREA_AVG,BASEMENTAREA_MEDI
18,LIVINGAPARTMENTS_AVG,LIVINGAPARTMENTS_MEDI,0.993578,80.349700,22.905800,LIVINGAPARTMENTS_AVG,LIVINGAPARTMENTS_MEDI
19,NONLIVINGAPARTMENTS_AVG,NONLIVINGAPARTMENTS_MEDI,0.993324,43.983001,0.000000,NONLIVINGAPARTMENTS_AVG,NONLIVINGAPARTMENTS_MEDI
20,PREV_APP_TOTAL_APPLICATION_AMOUNT,PREV_APP_TOTAL_CREDIT,0.992331,151.200500,100.194100,PREV_APP_TOTAL_APPLICATION_AMOUNT,PREV_APP_TOTAL_CREDIT
21,NONLIVINGAREA_AVG,NONLIVINGAREA_MEDI,0.991765,28.503400,0.000000,NONLIVINGAREA_AVG,NONLIVINGAREA_MEDI
22,LANDAREA_AVG,LANDAREA_MEDI,0.991314,81.297599,11.613900,LANDAREA_AVG,LANDAREA_MEDI
23,CC_MAX_CARD_MONTHS,CC_STATUS_ACTIVE_COUNT,0.990479,89.832699,109.532900,CC_STATUS_ACTIVE_COUNT,CC_MAX_CARD_MONTHS
24,YEARS_BUILD_MODE,YEARS_BUILD_MEDI,0.989319,30.187300,27.010800,YEARS_BUILD_MODE,YEARS_BUILD_MEDI
25,YEARS_BUILD_AVG,YEARS_BUILD_MODE,0.989279,0.000000,30.187300,YEARS_BUILD_MODE,YEARS_BUILD_AVG
26,CC_AVG_CARD_MONTHS,CC_STATUS_ACTIVE_COUNT,0.989229,360.359004,109.532900,CC_AVG_CARD_MONTHS,CC_STATUS_ACTIVE_COUNT
27,FLOORSMIN_MODE,FLOORSMIN_MEDI,0.988609,0.000000,0.000000,FLOORSMIN_MODE,FLOORSMIN_MEDI
28,FLOORSMAX_MODE,FLOORSMAX_MEDI,0.988143,64.960600,32.916800,FLOORSMAX_MODE,FLOORSMAX_MEDI
29,BUREAU_TOTAL_CREDIT_PROLONG,BUREAU_MAX_CREDIT_PROLONG,0.987547,0.000000,0.000000,BUREAU_TOTAL_CREDIT_PROLONG,BUREAU_MAX_CREDIT_PROLONG
30,AMT_CREDIT,AMT_GOODS_PRICE,0.986962,1665.080450,1510.727015,AMT_CREDIT,AMT_GOODS_PRICE
31,FLOORSMIN_AVG,FLOORSMIN_MODE,0.986039,82.471300,0.000000,FLOORSMIN_AVG,FLOORSMIN_MODE
32,PREV_APP_MAX_CREDIT,PREV_APP_MAX_GOODS_PRICE,0.985687,237.895201,16.854300,PREV_APP_MAX_CREDIT,PREV_APP_MAX_GOODS_PRICE
33,PREV_APP_MAX_APPLICATION_AMOUNT,PREV_APP_MAX_CREDIT,0.985657,179.306998,237.895201,PREV_APP_MAX_CREDIT,PREV_APP_MAX_APPLICATION_AMOUNT
34,FLOORSMAX_AVG,FLOORSMAX_MODE,0.985592,47.337698,64.960600,FLOORSMAX_MODE,FLOORSMAX_AVG
35,LANDAREA_MODE,LANDAREA_MEDI,0.982754,78.066600,11.613900,LANDAREA_MODE,LANDAREA_MEDI
36,ELEVATORS_MODE,ELEVATORS_MEDI,0.982547,48.831900,0.000000,ELEVATORS_MODE,ELEVATORS_MEDI
37,INSTALL_TOTAL_AMOUNT_DUE,INSTALL_TOTAL_AMOUNT_PAID,0.981490,656.946404,2047.672416,INSTALL_TOTAL_AMOUNT_PAID,INSTALL_TOTAL_AMOUNT_DUE
38,ENTRANCES_MODE,ENTRANCES_MEDI,0.980730,41.783798,27.113600,ENTRANCES_MODE,ENTRANCES_MEDI
39,NONLIVINGAPARTMENTS_MODE,NONLIVINGAPARTMENTS_MEDI,0.980491,59.844200,0.000000,NONLIVINGAPARTMENTS_MODE,NONLIVINGAPARTMENTS_MEDI
40,COMMONAREA_MODE,COMMONAREA_MEDI,0.979212,28.013000,26.978300,COMMONAREA_MODE,COMMONAREA_MEDI
41,ELEVATORS_AVG,ELEVATORS_MODE,0.978365,0.000000,48.831900,ELEVATORS_MODE,ELEVATORS_AVG
42,ENTRANCES_AVG,ENTRANCES_MODE,0.977674,21.841499,41.783798,ENTRANCES_MODE,ENTRANCES_AVG
43,COMMONAREA_AVG,COMMONAREA_MODE,0.977393,133.102001,28.013000,COMMONAREA_AVG,COMMONAREA_MODE
44,BASEMENTAREA_MODE,BASEMENTAREA_MEDI,0.977034,47.290801,43.733500,BASEMENTAREA_MODE,BASEMENTAREA_MEDI
45,APARTMENTS_MODE,APARTMENTS_MEDI,0.976936,16.625200,61.181400,APARTMENTS_MEDI,APARTMENTS_MODE
46,POS_CASH_LOANS,INSTALL_LOANS,0.976188,627.858499,74.798400,POS_CASH_LOANS,INSTALL_LOANS
47,PREV_APP_AVG_APPLICATION_AMOUNT,PREV_APP_AVG_CREDIT,0.976006,194.395802,234.183299,PREV_APP_AVG_CREDIT,PREV_APP_AVG_APPLICATION_AMOUNT
48,NONLIVINGAREA_MODE,NONLIVINGAREA_MEDI,0.975753,53.593600,0.000000,NONLIVINGAREA_MODE,NONLIVINGAREA_MEDI
49,LIVINGAPARTMENTS_MODE,LIVINGAPARTMENTS_MEDI,0.975295,105.359900,22.905800,LIVINGAPARTMENTS_MODE,LIVINGAPARTMENTS_MEDI
50,LANDAREA_AVG,LANDAREA_MODE,0.975284,81.297599,78.066600,LANDAREA_AVG,LANDAREA_MODE
51,LIVINGAREA_MODE,LIVINGAREA_MEDI,0.974952,108.045099,128.879801,LIVINGAREA_MEDI,LIVINGAREA_MODE
52,PREV_APP_TOTAL_APPLICATIONS,PREV_APP_CLIENT_REPEATER_COUNT,0.974283,86.134188,0.000000,PREV_APP_TOTAL_APPLICATIONS,PREV_APP_CLIENT_REPEATER_COUNT
53,NONLIVINGAPARTMENTS_AVG,NONLIVINGAPARTMENTS_MODE,0.974230,43.983001,59.844200,NONLIVINGAPARTMENTS_MODE,NONLIVINGAPARTMENTS_AVG
54,PREV_APP_CONTRACT_CONSUMER_LOANS_COUNT,PREV_APP_PORTFOLIO_POS_COUNT,0.973204,145.710501,55.625099,PREV_APP_CONTRACT_CONSUMER_LOANS_COUNT,PREV_APP_PORTFOLIO_POS_COUNT
55,LIVINGAREA_AVG,LIVINGAREA_MODE,0.972671,109.191603,108.045099,LIVINGAREA_AVG,LIVINGAREA_MODE
56,BASEMENTAREA_AVG,BASEMENTAREA_MODE,0.972316,114.965002,47.290801,BASEMENTAREA_AVG,BASEMENTAREA_MODE
57,APARTMENTS_AVG,APARTMENTS_MODE,0.972235,103.174300,16.625200,APARTMENTS_AVG,APARTMENTS_MODE
58,YEARS_BEGINEXPLUATATION_AVG,YEARS_BEGINEXPLUATATION_MODE,0.971931,160.842999,188.206300,YEARS_BEGINEXPLUATATION_MODE,YEARS_BEGINEXPLUATATION_AVG
59,LIVINGAPARTMENTS_AVG,LIVINGAPARTMENTS_MODE,0.969730,80.349700,105.359900,LIVINGAPARTMENTS_MODE,LIVINGAPARTMENTS_AVG
60,NONLIVINGAREA_AVG,NONLIVINGAREA_MODE,0.966810,28.503400,53.593600,NONLIVINGAREA_MODE,NONLIVINGAREA_AVG
61,YEARS_BEGINEXPLUATATION_MODE,YEARS_BEGINEXPLUATATION_MEDI,0.964005,188.206300,140.387750,YEARS_BEGINEXPLUATATION_MODE,YEARS_BEGINEXPLUATATION_MEDI
62,PREV_APP_STATUS_APPROVED_COUNT,INSTALL_LOANS,0.959630,190.601702,74.798400,PREV_APP_STATUS_APPROVED_COUNT,INSTALL_LOANS
63,CC_TOTAL_DRAWING_COUNT,CC_TOTAL_POS_DRAWING_COUNT,0.956616,393.285302,153.987898,CC_TOTAL_DRAWING_COUNT,CC_TOTAL_POS_DRAWING_COUNT
64,POS_CASH_AVG_INST,POS_CASH_AVG_FUTURE_INST,0.954820,180.510801,3142.508003,POS_CASH_AVG_FUTURE_INST,POS_CASH_AVG_INST
65,BUREAU_TOTAL_DEBT,BUREAU_MAX_DEBT,0.951965,239.657301,201.103498,BUREAU_TOTAL_DEBT,BUREAU_MAX_DEBT
66,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,0.951520,0.000000,492.107601,REGION_RATING_CLIENT_W_CITY,REGION_RATING_CLIENT

In [50]:
redundant_candidates = [
    'PREV_APP_MAX_GOODS_PRICE',
    'BUREAU_BALANCE_MIN_MONTH',
    'BUREAU_BALANCE_UNIQUE_CREDITS',
    'CC_AVG_CARD_DPD',
    'CC_MAX_CARD_DPD_RATE',
    'OBS_60_CNT_SOCIAL_CIRCLE',
    'CC_MAX_CARD_MONTHS',
    'FLOORSMAX_MEDI',
    'ENTRANCES_AVG',
    'COMMONAREA_MEDI',
    'LIVINGAREA_AVG',
    'APARTMENTS_MEDI',
    'BASEMENTAREA_MEDI',
    'LIVINGAPARTMENTS_MEDI',
    'LANDAREA_MEDI',
    'YEARS_BUILD_MEDI',
    'FLOORSMIN_MODE',
    'ELEVATORS_MODE',
    'NONLIVINGAREA_MEDI',
    'NONLIVINGAPARTMENTS_MEDI',
    'ELEVATORS_AVG',
    'COMMONAREA_MODE',
    'APARTMENTS_MODE',
    'LIVINGAREA_MODE',
    'BASEMENTAREA_MODE',
    'NONLIVINGAREA_MODE',
    'LIVINGAPARTMENTS_AVG',
    'NONLIVINGAREA_AVG',
    'YEARS_BEGINEXPLUATATION_AVG',
    'YEARS_BEGINEXPLUATATION_MEDI',
    'INSTALL_LOANS',
    'PREV_APP_PORTFOLIO_POS_COUNT',
    'CC_TOTAL_POS_DRAWING_COUNT',
    'POS_CASH_AVG_INST'
]

**Step 3 — Removal Candidates Set**

In [51]:
# Step 1: all original columns with zero total Gain
features_to_remove = set(
    zero_gain_original['Original_Feature']
)

# Step 2: manually reviewed redundancy candidates
features_to_remove.update(redundant_candidates)

print("Total features to remove:", len(features_to_remove))

Total features to remove: 82

**Step 4 - Selected Features**

In [52]:
selected_features = [
    col for col in X_train.columns
    if col not in features_to_remove
]

X_train_selected = X_train[selected_features].copy()
X_val_selected = X_val[selected_features].copy()

print("Original features:", X_train.shape[1])
print("Removed features:", len(features_to_remove))
print("Selected features:", len(selected_features))

Original features: 260
Removed features: 82
Selected features: 178

### **Recreating the Baseline model after the Feature Selection**

**Step 1 - Preprocessing Pipeline**

In [53]:
# Create the numerical and categorical lists again:

num_features_selected = X_train_selected.select_dtypes(
    include=['int64', 'float64']
).columns.tolist()

cat_features_selected = X_train_selected.select_dtypes(
    include=['object', 'category']
).columns.tolist()

print("Numerical:", len(num_features_selected))
print("Categorical:", len(cat_features_selected))

Numerical: 164
Categorical: 14

In [54]:
# Transformers

numeric_transformer_selected = Pipeline([
    ('imputer', SimpleImputer(strategy='median'))
])

categorical_transformer_selected = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(
        handle_unknown='ignore',
        drop='first',
        sparse_output=False
    ))
])

preprocessor_selected = ColumnTransformer([
    ('num', numeric_transformer_selected, num_features_selected),
    ('cat', categorical_transformer_selected, cat_features_selected)
])

**Step 2 - Baseline Models**

In [55]:
models_selected = {
    'Random Forest': RandomForestClassifier(
        n_estimators=100,
        random_state=42,
        class_weight='balanced',
        n_jobs=-1
    ),

    'XGBoost': XGBClassifier(
        n_estimators=100,
        random_state=42,
        eval_metric='logloss',
        n_jobs=-1
    ),

    'LightGBM': LGBMClassifier(
        n_estimators=100,
        random_state=42,
        verbosity=-1,
        n_jobs=-1
    )
}

In [56]:
trained_models_selected = {}
results_selected = []

for name, model in models_selected.items():

    print(f"Training {name}...")

    pipeline = Pipeline([
        ('preprocessor', preprocessor_selected),
        ('model', model)
    ])

    pipeline.fit(X_train_selected, y_train)

    trained_models_selected[name] = pipeline

    y_pred = pipeline.predict(X_val_selected)
    y_prob = pipeline.predict_proba(X_val_selected)[:, 1]

    results_selected.append({
        'Model': name,
        'ROC-AUC': roc_auc_score(y_val, y_prob),
        'Recall': recall_score(y_val, y_pred),
        'Precision': precision_score(y_val, y_pred),
        'F1-Score': f1_score(y_val, y_pred)
    })

results_selected_df = (
    pd.DataFrame(results_selected)
    .sort_values('ROC-AUC', ascending=False)
    .reset_index(drop=True)
)

display(results_selected_df)

Training Random Forest...
Training XGBoost...
Training LightGBM...

           Model   ROC-AUC    Recall  Precision  F1-Score
0       LightGBM  0.785531  0.040548   0.557196  0.075594
1        XGBoost  0.770211  0.067669   0.475472  0.118477
2  Random Forest  0.744475  0.002148   0.333333  0.004269

**Step 3 - compare before vs after feature selection**

In [57]:
baseline_before = results_df[
    ['Model', 'ROC-AUC', 'Recall']
].copy()

baseline_before = baseline_before.rename(columns={
    'ROC-AUC': 'ROC-AUC_Before',
    'Recall': 'Recall_Before'
})

baseline_after = results_selected_df[
    ['Model', 'ROC-AUC', 'Recall']
].copy()

baseline_after = baseline_after.rename(columns={
    'ROC-AUC': 'ROC-AUC_After',
    'Recall': 'Recall_After'
})

comparison = baseline_before.merge(
    baseline_after,
    on='Model'
)

comparison['ROC-AUC_Change'] = (
    comparison['ROC-AUC_After']
    - comparison['ROC-AUC_Before']
)

comparison['Recall_Change'] = (
    comparison['Recall_After']
    - comparison['Recall_Before']
)

comparison

,Model,ROC-AUC_Before,Recall_Before,ROC-AUC_After,Recall_After,ROC-AUC_Change,Recall_Change
0,LightGBM,0.784547,0.040279,0.785531,0.040548,0.000984,0.000269
1,XGBoost,0.769887,0.066058,0.770211,0.067669,0.000323,0.001611
2,Random Forest,0.741291,0.002148,0.744475,0.002148,0.003183,0.000000

### **Hyperparameter Tuning**

**1. LightGBM Model**

In [58]:
# LightGBM Pipeline

lgbm_pipeline = Pipeline([
    ('preprocessor', preprocessor_selected),
    ('model', LGBMClassifier(
        objective='binary',
        random_state=42,
        n_jobs=-1,
        verbosity=-1
    ))
])

In [59]:
# LightGBM search space

lgbm_param_dist = {
    'model__n_estimators': [100, 200, 300, 500],
    'model__learning_rate': [0.01, 0.03, 0.05, 0.1],
    'model__num_leaves': [15, 31, 50, 75],
    'model__max_depth': [-1, 5, 7, 10],
    'model__min_child_samples': [20, 50, 100, 200],
    'model__subsample': [0.7, 0.8, 0.9, 1.0],
    'model__colsample_bytree': [0.7, 0.8, 0.9, 1.0],
    'model__reg_alpha': [0, 0.1, 0.5, 1.0],
    'model__reg_lambda': [0, 0.1, 0.5, 1.0]
}

In [60]:
# RandomizedSearchCV for LightGBM

lgbm_search = RandomizedSearchCV(
    estimator=lgbm_pipeline,
    param_distributions=lgbm_param_dist,
    n_iter=10,
    scoring='roc_auc',
    cv=3,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

lgbm_search.fit(X_train_selected, y_train)

Fitting 3 folds for each of 10 candidates, totalling 30 fits

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('num',
                                                                               Pipeline(steps=[('imputer',
                                                                                                SimpleImputer(strategy='median'))]),
                                                                               ['AMT_INCOME_TOTAL',
                                                                                'AMT_CREDIT',
                                                                                'AMT_ANNUITY',
                                                                                'AMT_GOODS_PRICE',
                                                                                'REGION_POPULATION_RELATIVE',
                                                                                'DAYS_REGISTRATION',
                                                                                'DAYS_ID_PUBLISH',
                                                                                'OWN_CAR_AGE',
                                                                                'FLAG_WORK_PHONE',
                                                                                'FLAG_CONT_MOBILE'...
                                                                    0.9, 1.0],
                                        'model__learning_rate': [0.01, 0.03,
                                                                 0.05, 0.1],
                                        'model__max_depth': [-1, 5, 7, 10],
                                        'model__min_child_samples': [20, 50,
                                                                     100, 200],
                                        'model__n_estimators': [100, 200, 300,
                                                                500],
                                        'model__num_leaves': [15, 31, 50, 75],
                                        'model__reg_alpha': [0, 0.1, 0.5, 1.0],
                                        'model__reg_lambda': [0, 0.1, 0.5, 1.0],
                                        'model__subsample': [0.7, 0.8, 0.9,
                                                             1.0]},
                   random_state=42, scoring='roc_auc', verbose=1)

In [61]:
print("Best LightGBM ROC-AUC:", lgbm_search.best_score_)
print("Best LightGBM parameters:")
print(lgbm_search.best_params_)

Best LightGBM ROC-AUC: 0.7811512943090649
Best LightGBM parameters:
{'model__subsample': 0.7, 'model__reg_lambda': 1.0, 'model__reg_alpha': 1.0, 'model__num_leaves': 50, 'model__n_estimators': 300, 'model__min_child_samples': 200, 'model__max_depth': 7, 'model__learning_rate': 0.05, 'model__colsample_bytree': 0.8}

In [62]:
# Best lgbm train model
lgbm_best = lgbm_search.best_estimator_

In [63]:
y_lgbm_pred = lgbm_best.predict(X_val_selected)
y_lgbm_prob = lgbm_best.predict_proba(X_val_selected)[:, 1]

In [64]:
recall_lgbm = recall_score(y_val, y_lgbm_pred)
precision_lgbm = precision_score(y_val, y_lgbm_pred)
f1_lgbm = f1_score(y_val, y_lgbm_pred)
roc_auc_lgbm = roc_auc_score(y_val, y_lgbm_prob)

print("LightGBM Recall:", recall_lgbm)
print("LightGBM Precision:", precision_lgbm)
print("LightGBM F1-Score:", f1_lgbm)
print("LightGBM ROC-AUC:", roc_auc_lgbm)

LightGBM Recall: 0.04833512352309345
LightGBM Precision: 0.6
LightGBM F1-Score: 0.08946322067594434
LightGBM ROC-AUC: 0.7891650810302151

In [78]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_val, y_lgbm_pred))

Confusion Matrix:
[[42282   120]
 [ 3544   180]]

In [65]:
print(classification_report(y_val, y_lgbm_pred))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96     42402
           1       0.60      0.05      0.09      3724

    accuracy                           0.92     46126
   macro avg       0.76      0.52      0.52     46126
weighted avg       0.90      0.92      0.89     46126

**2. XGBoost Model**

In [66]:
# XGBoost Pipeline

xgb_pipeline = Pipeline([
    ('preprocessor', preprocessor_selected),
    ('model', XGBClassifier(
        objective='binary:logistic',
        eval_metric='logloss',
        random_state=42,
        n_jobs=-1
    ))
])

In [67]:
# XGBoost search space

xgb_param_dist = {
    'model__n_estimators': [100, 200, 300, 500],
    'model__learning_rate': [0.01, 0.03, 0.05, 0.1],
    'model__max_depth': [3, 4, 5, 6, 8],
    'model__min_child_weight': [1, 3, 5, 10],
    'model__subsample': [0.7, 0.8, 0.9, 1.0],
    'model__colsample_bytree': [0.7, 0.8, 0.9, 1.0],
    'model__gamma': [0, 0.1, 0.3, 0.5],
    'model__reg_alpha': [0, 0.1, 0.5, 1.0],
    'model__reg_lambda': [1, 2, 5, 10]
}

In [68]:
# RandomizedSearchCV for XGBoost

xgb_search = RandomizedSearchCV(
    estimator=xgb_pipeline,
    param_distributions=xgb_param_dist,
    n_iter=10,
    scoring='roc_auc',
    cv=3,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

xgb_search.fit(X_train_selected, y_train)

Fitting 3 folds for each of 10 candidates, totalling 30 fits

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('num',
                                                                               Pipeline(steps=[('imputer',
                                                                                                SimpleImputer(strategy='median'))]),
                                                                               ['AMT_INCOME_TOTAL',
                                                                                'AMT_CREDIT',
                                                                                'AMT_ANNUITY',
                                                                                'AMT_GOODS_PRICE',
                                                                                'REGION_POPULATION_RELATIVE',
                                                                                'DAYS_REGISTRATION',
                                                                                'DAYS_ID_PUBLISH',
                                                                                'OWN_CAR_AGE',
                                                                                'FLAG_WORK_PHONE',
                                                                                'FLAG_CONT_MOBILE'...
                   param_distributions={'model__colsample_bytree': [0.7, 0.8,
                                                                    0.9, 1.0],
                                        'model__gamma': [0, 0.1, 0.3, 0.5],
                                        'model__learning_rate': [0.01, 0.03,
                                                                 0.05, 0.1],
                                        'model__max_depth': [3, 4, 5, 6, 8],
                                        'model__min_child_weight': [1, 3, 5,
                                                                    10],
                                        'model__n_estimators': [100, 200, 300,
                                                                500],
                                        'model__reg_alpha': [0, 0.1, 0.5, 1.0],
                                        'model__reg_lambda': [1, 2, 5, 10],
                                        'model__subsample': [0.7, 0.8, 0.9,
                                                             1.0]},
                   random_state=42, scoring='roc_auc', verbose=1)

In [69]:
print("Best XGBoost ROC-AUC:", xgb_search.best_score_)
print("Best XGBoost parameters:")
print(xgb_search.best_params_)

Best XGBoost ROC-AUC: 0.7796879607667346
Best XGBoost parameters:
{'model__subsample': 0.8, 'model__reg_lambda': 5, 'model__reg_alpha': 1.0, 'model__n_estimators': 200, 'model__min_child_weight': 1, 'model__max_depth': 8, 'model__learning_rate': 0.05, 'model__gamma': 0.3, 'model__colsample_bytree': 0.8}

In [70]:
# Best xgb train model
xgb_best = xgb_search.best_estimator_

In [71]:
y_xgb_pred = xgb_best.predict(X_val_selected)
y_xgb_prob = xgb_best.predict_proba(X_val_selected)[:, 1]

In [72]:
recall_xgb = recall_score(y_val, y_xgb_pred)
precision_xgb = precision_score(y_val, y_xgb_pred)
f1_xgb = f1_score(y_val, y_xgb_pred)
roc_auc_xgb = roc_auc_score(y_val, y_xgb_prob)

print("XGBoost Recall:", recall_xgb)
print("XGBoost Precision:", precision_xgb)
print("XGBoost F1-Score:", f1_xgb)
print("XGBoost ROC-AUC:", roc_auc_xgb)

XGBoost Recall: 0.04054779806659506
XGBoost Precision: 0.5992063492063492
XGBoost F1-Score: 0.07595573440643863
XGBoost ROC-AUC: 0.7869902867196494

In [77]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_val, y_xgb_pred))

Confusion Matrix:
[[42301   101]
 [ 3573   151]]

In [73]:
print(classification_report(y_val, y_xgb_pred))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96     42402
           1       0.60      0.04      0.08      3724

    accuracy                           0.92     46126
   macro avg       0.76      0.52      0.52     46126
weighted avg       0.90      0.92      0.89     46126

## **Check Thresholds**

In [74]:
thresholds = np.arange(0.10, 0.51, 0.05)

threshold_results = []

for threshold in thresholds:

    y_lgbm_pred_threshold = (
        y_lgbm_prob >= threshold
    ).astype(int)

    threshold_results.append({
        'Threshold': threshold,
        'Recall': recall_score(
            y_val,
            y_lgbm_pred_threshold,
            zero_division=0
        ),
        'Precision': precision_score(
            y_val,
            y_lgbm_pred_threshold,
            zero_division=0
        ),
        'F1-Score': f1_score(
            y_val,
            y_lgbm_pred_threshold,
            zero_division=0
        )
    })

threshold_df = pd.DataFrame(threshold_results)

display(threshold_df)

   Threshold    Recall  Precision  F1-Score
0       0.10  0.632922   0.210465  0.315888
1       0.15  0.476369   0.268462  0.343399
2       0.20  0.350698   0.315307  0.332062
3       0.25  0.260473   0.363977  0.303647
4       0.30  0.186627   0.398967  0.254299
5       0.35  0.136950   0.442708  0.209188
6       0.40  0.097744   0.480845  0.162464
7       0.45  0.070086   0.526210  0.123697
8       0.50  0.048335   0.600000  0.089463

* The classification threshold was reduced from 0.50 to 0.15 to improve default detection. This increased Recall substantially, while maintaining a better balance between Recall and Precision, as reflected by the highest F1-score among the tested thresholds.

* I would not choose 0.10 just because Recall is highest. It sacrifices too much Precision compared with 0.15.

# **Final Test Result**

**Evaluate the already-tuned LightGBM + Threshold 0.15 on the untouched test set.**

In [75]:
# Final test probabilities
y_test_prob = lgbm_best.predict_proba(
    X_test[selected_features]
)[:, 1]

# Apply selected validation threshold
final_threshold = 0.15

y_test_pred = (
    y_test_prob >= final_threshold
).astype(int)

In [76]:
print("Final Test ROC-AUC:",
      roc_auc_score(y_test, y_test_prob))

print("Final Test Recall:",
      recall_score(y_test, y_test_pred))

print("Final Test Precision:",
      precision_score(y_test, y_test_pred))

print("Final Test F1:",
      f1_score(y_test, y_test_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))

Final Test ROC-AUC: 0.7866257360294081
Final Test Recall: 0.4675080558539205
Final Test Precision: 0.2653963414634146
Final Test F1: 0.33858420847919096

Confusion Matrix:
[[37584  4819]
 [ 1983  1741]]

## **Final Model Evaluation**

After feature selection and hyperparameter tuning, LightGBM was selected as the final model based on its validation ROC-AUC performance. The classification threshold was then optimized on the validation set to improve default detection, and a threshold of **0.15** was selected based on the Recall–Precision trade-off and the highest F1-score among the evaluated thresholds.

The final model was evaluated once on the untouched test set.

| Metric    | Test Performance |
| --------- | ---------------: |
| ROC-AUC   |       **0.7866** |
| Recall    |       **46.75%** |
| Precision |       **26.54%** |
| F1-Score  |       **33.86%** |

The confusion matrix was:

* True Negatives: **37,584**
* False Positives: **4,819**
* False Negatives: **1,983**
* True Positives: **1,741**

The final ROC-AUC of **0.7866** indicates that the model provides useful ranking ability for distinguishing defaulters from non-defaulters. Using the optimized threshold of **0.15** substantially improved Recall compared with the default 0.50 threshold, allowing the model to identify a larger proportion of actual defaulters while accepting a reduction in Precision.

Overall, the final model prioritizes **default detection and Recall** rather than maximizing Precision alone, which is appropriate for this credit-risk use case.

## **Save the final model**

In [80]:
final_model_artifact = {
    "model": lgbm_best,
    "selected_features": selected_features,
    "threshold": 0.15
}

joblib.dump(
    final_model_artifact,
    "home_credit_final_model.pkl"
)

['home_credit_final_model.pkl']